version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8081:80"
    environment:
      - PORT=80
  api:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
