version: "3"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - PORT=80
    command: nginx -g 'daemon off;'
